version: '3.8'

services:
  zest-service:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  redis-cli:
    image: redis:latest
    depends_on:
      - redis
    entrypoint: ["redis-cli", "-h", "redis"]
